version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enrollment-service
    ports:
      - '3003:3003'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL:-http://payment-service:3004/api/v1}
    restart: unless-stopped
    networks:
      - edu-forge-network
    command: >
      sh -c "until nc -z postgres 5432; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready!';
      npx prisma db push --accept-data-loss && node dist/src/main.js"

  postgres:
    image: postgres:17
    container_name: edu-forge-enroll-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - edu-forge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  edu-forge-network:
    external: true
